### PR TITLE
CORS

### PR DESCRIPTION
**Pull request by x37v**
This allows for browser based requests to a libossia http server... so that we can create browser based UIs that do OSCQuery discovery.

https://developer.mozilla.org/en-US/docs/Glossary/CORS

### CODE REVIEW

**Comment by x37v** [comment]
I guess I should rebase on origin? maybe just cherry-pick that commit if you want it?

**Comment by jcelerier** [comment]
Looks good, thanks ! If I understand correctly this means that a web page  on e.g. example.com will accept to do a request to an oscquery server located at bar.com:1234, right ?

**Comment by jcelerier** [comment]
indeed since it's one line I'll just cherry-pick it on master

**Comment by jcelerier** [comment]
I imagine there are some security implications around this, I'll add it to the (upcoming) github kanban board regarding network security in libossia so that we can review more in depth if for instance there are settings that should be provided to the user, etc... in the meantime thanks for the patch !

**Comment by x37v** [comment]
> Looks good, thanks ! If I understand correctly this means that a web page on e.g. example.com will accept to do a request to an oscquery server located at bar.com:1234, right ?

yeah, its a browser that controls the acceptance or not but, exactly... a webpage served from `example.com` can do an HTTP request to an oscquery http server `bar.com:5678` (i changed to default ports)

the `*` just allows any webpage to do the request.. `example.com` `foo.com` `localhost` etc.

**Comment by x37v** [comment]
> I imagine there are some security implications around this, I'll add it to the (upcoming) github kanban board regarding network security in libossia so that we can review more in depth if for instance there are settings that should be provided to the user, etc... in the meantime thanks for the patch !

yeah, maybe this would want to be a configurable thing eventually.. but in the short term, i'm excited to make some web based UI for my libossia based project!

**Pull request closed without merging**
