### PR TITLE
Merging feature/raw_serial into master

### PR DESCRIPTION
**Pull request by thibaudk**
This allows to use the "raw" argument in the "onMessage" function for serial devices.

Here is a use case of communication between score and the "AnalogInOutSerial" Arduino example
(the arduino website seem to be missing the tutorial pages where the sketch can be found. In the IDE and the online editor, it is under BUILT-IN / ANALOG)

```
/*
 * AnalogInOutSerial.qml
 * This example comunicates with the arduino sketch of the same name
 * you can find this corresponding example sketch on the arduino website
 * visit: https://www.arduino.cc/en/Tutorial/BuiltInExamples
 * These examples are included in the Arduino IDE
 * as well as in the Web Editor under Examples/BUILT IN
 * for any issue on the ossia-score side, please report to:
 * https://github.com/OSSIA/score-user-library/issues
 */

import QtQuick 2.0
import Ossia 1.0 as Ossia

Ossia.Serial
{
    function openListening(address) {}
    function closeListening(address) {}

    property string buffer: "";

    function handleDelimiter(stream, delimiter, execute) {
        var formated = ""; // a variable to store the message in the delimited format

        buffer += stream; // store incomming characters as they arrive

        for(var i = 0; i <= buffer.length; ++i) {
            if(buffer[i] !== delimiter) {
                if(buffer[i] !== undefined) {
                    formated += buffer[i]; }
                // add stored characters one by one to the formated variable if they are defined and different from the delimiter
            } else {
                execute(formated);
                formated = "";
                // if the current character in the buffer is the delimiter, pass "fomated" to the function before emptying the string
            }
        }

        buffer = formated; // reset the buffer to contain the incomplete formated message if any
                           //to be complete with the next incomming characters in the stream
    }

    property var splitedStream : [];

    function onMessage(message, raw) { // evaluated each time a message is received

        handleDelimiter(raw, '\n',
                        function(delimited) {
                            splitedStream = delimited.split(/[\t=]/); // split at the '\t' and '=' characters to seperate each elements
                        }
        )

        return [{address: "/ "+splitedStream[0], value: parseInt(splitedStream[1])}, // assign values to namespaces in the tree
        {address: "/"+splitedStream[2], value: parseInt(splitedStream[3])}];
    }

    function createTree() {
        return [
        {
            name: " sensor ",
            type:  Ossia.Type.Int,
            min: 0,
            max: 1023,
            access: Ossia.Access.Get,
            bounding: Ossia.Bounding.Clip,
            repetition_filter: Ossia.Repetitions.Filtered
        },
        {
            name: " output ",
            type:  Ossia.Type.Int,
            min: 0,
            max: 255,
            access: Ossia.Access.Get,
            bounding: Ossia.Bounding.Clip,
            repetition_filter: Ossia.Repetitions.Filtered
        }
        ];
    }
}
```

### CODE REVIEW

**Comment by jcelerier** [comment]
hmm, I'm wondering if it wouldn't be nice if the "handleDelimiter", "buffer" and "splitedStream" ("splitStream" is enough I think) were part of the ossia.serial object directly (which is at the end of this file here : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-qt/serial/serial_protocol.hpp) but this would mean porting that part of the code in C++.

Also I think that to make the API simpler (and more performant), there should actually be two functions : onMessage which keeps the existing behaviour for backward compatibility and has only a "message" parameter splitted on "\n", and onRawMessage which would only have the "raw" parameter to make stuff simpler for the user and prevent misuse - e.g. in your example you would write `function onRawMessage(raw) { ... }`  instead of `function onMessage(message, raw) { ... }` 

What do you think ?

**Comment by thibaudk** [comment]
Yes this would be much better indeed !
I will happily attempt the port to C++ even tho I still suck at it bad.
I imagine however that all the elements for creating the onRawMessage function are already there and only require to be moved around in both master and feature/raw_serial.

**Comment by thibaudk** [comment]
Turns out it is also very important to implement the "rate" parameter, similar to OSCQuerry and OSC. The serial port is very easy to saturate.

**Comment by avilleret** [comment]
should we merge this one ? @jcelerier & @thibaudk

**Comment by jcelerier** [comment]
nope, it's not finished yet

**Comment by thibaudk** [comment]
Jesus ! more than a year and I still haven't moved an inch !
Very sorry, I have to get to it. I will

**Comment by jcelerier** [comment]
welcome to open-source software development ^_^

**Comment by jcelerier** [comment]
maybe you should reopen the pr ?

**Comment by thibaudk** [comment]
Yes, soon as I have what I need to test

**Pull request closed without merging**
