### PR TITLE
use GIT_EXECUTABLE

### PR DESCRIPTION
**Pull request by x37v**
I'm running git `3.27.3` on a mac, initial cmake setup fails for me on master, this resolves that.

### CODE REVIEW

**Comment by jcelerier** [comment]
thanks!
I'm curious, doesn't Git::Git work for you? I changed the git calls to this one recently (except the one I missed, thanks for noiticing it) as it gives a much more obvious error when not found in cmake-side

**Comment by x37v** [comment]
no, Git::Git doesn't work for me, that is why I needed this change to get the build going again.

**Comment by x37v** [comment]
searching github, I'm not finding others using `Git::Git` as the alias for the git executable in the same way..

https://github.com/search?q=%22Git%3A%3AGit%22+language%3Acmake&type=code

**Comment by jcelerier** [comment]
Okay, I had gotten it from cmake's module, apparently it's here since 3.14 (https://cmake.org/cmake/help/latest/module/FindGit.html) so strange that it did not work for you.. maybe a CMake bug to report. In any case merging, thanks for the patch!

**Pull request merged**
