### PR TITLE
Add a configuration file for ossia max

### PR DESCRIPTION
**Pull request by jcelerier**
Content:

    { "default_deferlow": false }

Location:

- On Mac:

    ~/Library/Application Support/ossia-max/ossia-max.conf

- On Win:

    ~/Application Data/ossia-max/ossia-max.conf

### CODE REVIEW

**Comment by jcelerier** [comment]
havent tested on windows yet, I was doing it over ssh on my mac

**Review by avilleret — COMMENTED** [review]
looks good to me
need to test on windows

maybe we could also write the config file on exit and add a setter through [ossia] object
but not sure it's relevant since we can then screw up configuration file by opening a patcher which overrides local setting...

**Comment by jcelerier** [comment]
yup I was not sure about if it should write one if there isn't. maybe we can add later if needed !

**Comment by jcelerier** [comment]
> but not sure it's relevant since we can then screw up configuration file by opening a patcher which overrides local setting...

oh yes

**Comment by avilleret** [comment]
instead of accessing this configuration through [ossia] object, we could provide a configuration patcher in extras folder that uses some js magic to write this file on disk

**Comment by jcelerier** [comment]
okay, checked (and fixed) on win32

**Pull request merged**
